### PR TITLE
Editorial: Remove duplicate full stops

### PR DESCRIPTION
**Pull request by jamierocks**

### CODE REVIEW

**Review by syg — APPROVED** [review]
Nice cleanup, thank you.

**Comment by syg** [comment]
Unfortunately https://github.com/tc39/proposal-resizablearraybuffer/commit/013e6e9821a7603e4a3a2cd3b06955146079fec5 rebased against the tip-of-tree ecma262 spec and this PR also needs rebasing. Let me know if you don't have cycles for it, and I can rebase it for you.

**Comment by jamierocks** [comment]
No worries, I'll rebase when I get back from work :)

**Comment by jamierocks** [comment]
I've rebased this :)

**Review by syg — APPROVED** [review]

**Pull request merged**
