### PR TITLE
Editorial: improve desc. of abstract operation

### PR DESCRIPTION
**Pull request by jugglinmike**
Following up on [this conversation](https://github.com/tc39/proposal-resizablearraybuffer/pull/66#issuecomment-905963860).

### CODE REVIEW

**Review by syg — APPROVED** [review]

**Comment by syg** [comment]
Due to the update to using structured headers, this now needs a rebase. I'd be glad to rebase it myself but I don't have access to push to the upstream branch. @jugglinmike could you please rebase or give maintainers access to the PR?

**Comment by ljharb** [comment]
Since it comes from bocoup's fork instead of mike's, they'd have to add you directly to the bocoup fork to provide that access.

**Comment by jugglinmike** [comment]
@syg Updated!

**Comment by syg** [comment]
> @syg Updated!

Thank you, but it looks like there're still conflicts that is blocking merge.

**Comment by jugglinmike** [comment]
That's strange; GitHub is telling me that there are no conflicts:

image

**Comment by syg** [comment]
Oh I see, it was not possible to be rebased but it can be squashed.

**Pull request merged**
