### PR TITLE
Normative: correct derivation of SAB "allocLength"

### PR DESCRIPTION
**Pull request by jugglinmike**

### CODE REVIEW

**Review by syg — COMMENTED** [review]
This is intentional. See the NOTE right below about why a data block is allocated with _maxByteLength_.

**Comment by jugglinmike** [comment]
As I understand that note, it explains why "allocLength" sometimes takes the value of "maxByteLength." The part that still confuses me is why "maxByteLength" is used when it is *not* present.

For ECMAScript functions, unused optional parameters take the value of `undefined`, but I don't think that holds for the spec's abstract operations. It's not defined by [the Algorithm Conventions section](https://tc39.es/ecma262/#sec-algorithm-conventions), and I can't find any existing uses of an optional AO parameter value when the parameter isn't present.

If that is what's intended, then I'd suggest re-writing the second branch to read:

> 6. Else, let allocLength be undefined.

...but I get the sense that the intent is to allocate either "maxByteLength" if it is present or "byteLength" otherwise.

**Comment by syg** [comment]
My apologies, your sense was correct and I misread the PR. This branch is backwards.

**Comment by jugglinmike** [comment]
No worries!

**Pull request merged**
