### PR TITLE
Normative: Fix detach check for TypedArray.prototype.transfer

### LINKED ISSUE #98: `transfer` is missing a detach check after converting parameter
n/t

### PR DESCRIPTION
**Pull request by syg**
Closes #98

### CODE REVIEW

**Comment by bakkot** [comment]
I note that this order (coerce argument, then check for detachedness) is inconsistent with [`TypedArray.prototype.at`](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-%typedarray%.prototype.at), which does the detachedness check before the argument coercion.

But I don't actually care, this seems fine.

**Comment by syg** [comment]
> I note that this order (coerce argument, then check for detachedness) is inconsistent with [TypedArray.prototype.at](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-%typedarray%.prototype.at), which does the detachedness check before the argument coercion.

This is true. In `at`, if the parameter coercion detaches the buffer, it's "fine" to not do a second detach check because there's a reasonable behavior even for detached buffers: return undefined.

In `transfer`, the operation itself needs to detach the source buffer after transferring, so it needs to know for sure the buffer is attached before continuing. Putting the detached check before the parameter coercion means we do one before then another one right after, which seems... not very useful?

**Comment by bakkot** [comment]
Yeah, works for me. Just wanted to note the inconsistency.

**Comment by syg** [comment]
This got consensus at the July TC39 plenary.

**Pull request merged**
